---

- name: Download Brim
  ansible.builtin.get_url:
    url: "{{ brim_pkg }}"
    checksum: "{{ brim_checksum | default(omit) }}"
    dest: "/var/tmp"
    mode: '0644'
  register: dl_result
  until: dl_result is success

- name: Debian | update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: "{{ brim_apt_cache_valid_time | default(3600) }}"
  when: ansible_os_family == 'Debian'

- name: Install brim dependencies
  ansible.builtin.package:
    name: "{{ brim_deps | default([]) }}"
    state: present

- name: Debian | Install brim package
  ansible.builtin.apt:
    deb: "/var/tmp/{{ brim_pkg | basename }}"
    state: present
  when: ansible_os_family == 'Debian'

- name: Non-Debian | Install brim package
  ansible.builtin.package:
    name: "/var/tmp/{{ brim_pkg | basename }}"
    state: present
    disable_gpg_check: "{{ brim_rpm_disable_gpg_check | default('yes') }}"
  when: ansible_os_family != 'Debian'

- name: Add Brim applications desktop shortcut
  ansible.builtin.copy:
    src: brim.desktop
    dest: /usr/share/applications/
    mode: '0644'
