---
# tasks file for juju4.brim

- name: Include version-specific variables for OS family.
  include_vars: "{{ ansible_os_family }}.yml"

- import_tasks: brim-linux.yml
  when: ansible_os_family != "Windows" and ansible_os_family != 'Darwin'

- import_tasks: brim-darwin.yml
  when: ansible_os_family == 'Darwin'

- import_tasks: brim-windows.yml
  when: ansible_os_family == "Windows"
