---

- name: Verify
  hosts: brim
  gather_facts: false
  tasks:
    - name: Gather package facts
      package_facts:
        manager: auto
    - name: Validate that needed packages are present
      assert:
        that: ansible_facts.packages['brim']
